[project]
name = "WebSearcher"
version = "0.4.8.dev2"
packages = [{include = "WebSearcher"}]
description = "Tools for conducting, collecting, and parsing web search"
authors = [{name = "Ronald E. Robertson", email = "<rer@acm.org>"}]
keywords = ["web", "search", "parser"]
license = "GPL-3.0"
readme = "README.md"
requires-python = ">=3.9"
# dynamic = ["version"]
dependencies = [
    "requests>=2.32.3",
    "lxml>=5.3.0",
    "beautifulsoup4>=4.12.3",
    "tldextract>=5.1.2",
    "brotli>=1.1.0",
    "pydantic>=2.9.2",
    "pandas>=2.2.3",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3.3",
    "syrupy>=4.7.1",
    "pandas>=2.2.3",
    "ipykernel>=6.29.5"
]

[project.urls]
homepage = "http://github.com/gitronald/WebSearcher"
repository = "http://github.com/gitronald/WebSearcher"

[project.scripts]
demo-search = 'scripts.demo_search:main'

# [tool.poetry]
# name = "WebSearcher"
# version = "0.4.8.dev2"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
