[version]
current = "0.1.27-d"

# Must match current_version
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  (\-
    (?P<extra>.+)
  )?
  '''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

# Add [[file]] configs 
[[file]]
src = "setup.py" # path relative tbump.toml
version_template = '{major}.{minor}.{patch}-{extra}'
# search = "version_info = {current_version}" # search string
