name: Python Package Release

on:
  push:
    branches:
      - master  # or your release branch
    tags:
      - 'v*'  # Trigger workflow on version tags e.g., v1.0, v2.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel twine
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: |
        # Add commands to run your tests here
        echo "Running tests"  # Placeholder for test commands

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    - name: Publish package to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_PASSWORD }}
        repository_url: https://upload.pypi.org/legacy/  # PyPI upload URL

